# Generated by Django 4.1.7 on 2023-03-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="main_image",
            field=models.ImageField(upload_to="images"),
        ),
        migrations.AlterField(
            model_name="author",
            name="avatar",
            field=models.ImageField(upload_to="avatars"),
        ),
    ]
